// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aatqokpwjlqyqrmiffge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdHFva3B3amxxeXFybWlmZmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzYxMTgsImV4cCI6MjA2OTYxMjExOH0.D3j253BCXTj1fw6tEIz4nGhMzeMqzMqdKa3xb4UHTsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});